#!/usr/bin/env sh
set -e

export ENVIRONMENT=${ENVIRONMENT:-development}

export EXPRESS_DEBUG_LEVEL=${EXPRESS_DEBUG_LEVEL:-info}
export EXPRESS_SOCKET=${EXPRESS_SOCKET:-/var/run/express.sock}
export NGINX_DEBUG_LEVEL=${NGINX_DEBUG_LEVEL:-info}
export NGINX_SERVER_ROOT=${NGINX_SERVER_ROOT:-/app}
export NGINX_SERVER_STATIC=${NGINX_SERVER_STATIC:-/static}
export NGINX_SERVER_LISTEN_PORT=${NGINX_SERVER_LISTEN_PORT:-80}
export NGINX_HEALTH_CHECK_PATH=${NGINX_HEALTH_CHECK_PATH:-/health}


# Configure Nginx
NGINX_CONFIG=/etc/nginx/nginx.conf
cp ${NGINX_CONFIG}.tmpl ${NGINX_CONFIG}
sed -i "s|\$NGINX_DEBUG_LEVEL|${NGINX_DEBUG_LEVEL}|g" ${NGINX_CONFIG}

NGINX_SERVER_CONFIG=/etc/nginx/conf.d/default.conf
cp ${NGINX_SERVER_CONFIG}.tmpl ${NGINX_SERVER_CONFIG}
sed -i "s|\$EXPRESS_SOCKET|${EXPRESS_SOCKET}|g" ${NGINX_SERVER_CONFIG}
sed -i "s|\$NGINX_SERVER_ROOT|${NGINX_SERVER_ROOT}|g" ${NGINX_SERVER_CONFIG}
sed -i "s|\$NGINX_SERVER_STATIC|${NGINX_SERVER_STATIC}|g" ${NGINX_SERVER_CONFIG}
sed -i "s|\$NGINX_SERVER_LISTEN_PORT|${NGINX_SERVER_LISTEN_PORT}|g" ${NGINX_SERVER_CONFIG}
sed -i "s|\$NGINX_HEALTH_CHECK_PATH|${NGINX_HEALTH_CHECK_PATH}|g" ${NGINX_SERVER_CONFIG}


echo "Run command \"$@\""
exec "$@"
